//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SporSalonuEntities : DbContext
    {
        public SporSalonuEntities()
            : base("name=SporSalonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arka_Bacak> Arka_Bacak { get; set; }
        public virtual DbSet<Arka_Pazı> Arka_Pazı { get; set; }
        public virtual DbSet<Baldır> Baldır { get; set; }
        public virtual DbSet<Göğüs> Göğüs { get; set; }
        public virtual DbSet<Hareket> Hareket { get; set; }
        public virtual DbSet<Kanat> Kanat { get; set; }
        public virtual DbSet<Karın> Karın { get; set; }
        public virtual DbSet<Omuz> Omuz { get; set; }
        public virtual DbSet<Ön_Bacak> Ön_Bacak { get; set; }
        public virtual DbSet<Ön_Kol> Ön_Kol { get; set; }
        public virtual DbSet<Ön_Pazı> Ön_Pazı { get; set; }
        public virtual DbSet<Program> Program { get; set; }
        public virtual DbSet<Uye> Uye { get; set; }
    }
}
