//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notlar
    {
        public int NotID { get; set; }
        public Nullable<int> OgrID { get; set; }
        public Nullable<int> DersID { get; set; }
        public Nullable<int> NotSkor { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
    }
}
